# Generated by Django 4.2.5 on 2023-09-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInicio', '0002_alter_adopcion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='imagen',
            field=models.ImageField(upload_to='adoption_images/'),
        ),
    ]
