# Generated by Django 4.2.5 on 2023-09-22 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppInicio', '0006_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='pub_date',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='contenido',
        ),
        migrations.AddField(
            model_name='pet',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='imagen',
            field=models.ImageField(default=1, upload_to='pet_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='edad',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
